### ISSUE TITLE
windowtrees.py error

### ISSUE THREAD

**Issue by cnxiaobo94** [achimklittich/WindowTrees#1]
Hi, when I run the windowtrees.py, some error occurred as below:
>>>
Traceback (most recent call last):
  File "../../../../../software/WindowTrees-main/windowtrees.py", line 287, in <module>
    run_windowtrees(inputfile, outdir, outgroup, windowsize, nthres, ncpus)
  File "../../../../../software/WindowTrees-main/windowtrees.py", line 253, in run_windowtrees
    os.rmdir(msa_path)
OSError: [Errno 39] Directory not empty: '/public/home/cug2202010039/workspace/wg_analyses/procapra/gazwg/windowtrees/6modern_swt_50kb/MSA'
>>>
Could you please do me a favor?

**Comment by achimklittich** [comment]
Hey, can you please check if the MSA folder is not empty? 
Which pyhton version did you use?
It is possible that files have remained in the folder due to repeated runs. Separate output folders should be defined for each run.
If that does not help you can contact me here again.

**Comment by cnxiaobo94** [comment]
> Hey, can you please check if the MSA folder is not empty? Which pyhton version did you use? It is possible that files have remained in the folder due to repeated runs. Separate output folders should be defined for each run. If that does not help you can contact me here again.

Hello, thanks for your reply.
1. I just checked that the MSA folder is empty. In the output dir, there are two folders ('MSA' and 'tmp') and a log file ('MSA_windowstats.out'). 'MSA' is an empty folder (it was not empty before the error occurred), while the 'tmp' has thousands of files like 'SJYE01000001.1.fa_VS-3023_400001-500000.fa'.
2. Python 3.7.12.
3. If the 'each run' means each value of window size, I did. when I chose a new window size, I made a new output-dir via 'mkdir'. But the same error occurred every time.

**Comment by achimklittich** [comment]
I've successfully executed the script on a sample dataset and everything functioned as expected. To ensure smooth operation, could you confirm that the input folder is free from any empty scaffolds or sequences within the fasta files? Also, if you're planning to rerun the script with identical parameters, it's important to choose a different output folder, as the script is designed to work with an empty output directory.

Regarding the MSA folder, if it's empty, you should be able to delete it without any issues, as it's not essential for the final output. If you're still facing difficulties in deleting the MSA folder, it might be worthwhile to check for any hidden files within it. Alternatively, you have the option to bypass this step by commenting out line 253 in the windowtrees.py Python script.

**Comment by cnxiaobo94** [comment]
> I've successfully executed the script on a sample dataset and everything functioned as expected. To ensure smooth operation, could you confirm that the input folder is free from any empty scaffolds or sequences within the fasta files? Also, if you're planning to rerun the script with identical parameters, it's important to choose a different output folder, as the script is designed to work with an empty output directory.
> 
> Regarding the MSA folder, if it's empty, you should be able to delete it without any issues, as it's not essential for the final output. If you're still facing difficulties in deleting the MSA folder, it might be worthwhile to check for any hidden files within it. Alternatively, you have the option to bypass this step by commenting out line 253 in the windowtrees.py Python script.

Thank you !!!  As you suggested, I commented out line 253 and the program is working as expected.
